apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-kube-prometheus-stack.yaml
  - application-loki.yaml
  - application-promtail.yaml
  - application-otel-collector.yaml
  - application-dashboards.yaml
  - application-grafana-ingress.yaml
  - application-alert-rules.yaml
